homebase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('homes/', views.homes_index, name='index'),
    path('homes/<int:home_id>/', views.homes_detail, name='detail'),
    path('homes/create', views.HomeCreate.as_view(), name='homes_create'),
    path('homes/<int:pk>/update/', views.HomeUpdate.as_view(), name='homes_update'),
    path('homes/<int:pk>/delete/', views.HomeDelete.as_view(), name='homes_delete'),
    path('homes/<int:home_id>/add_photo/', views.add_photo, name='add_photo'),
    path('homes/<int:home_id>/assoc_amenity/<int:amenity_id>/', views.assoc_amenity, name='assoc_amenity'),
    
    path('amenities/', views.AmenityList.as_view(), name='amenities_index'),
    
    path('amenitites/<int:pk>/', views.AmenityDetail.as_view(), name='amenities_detail'),
    path('amenitites/<int:pk>/', views.AmenityDetail.as_view(), name='amenity_detail'),
    
    path('amenities/create/', views.AmenityCreate.as_view(), name='amenities_create'),
    
    path('amenities/<int:pk>/update/', views.AmenityUpdate.as_view(), name='amenities_update'),
    
    path('amenities/<int:pk>/delete/', views.AmenityDelete.as_view(), name='amenities_delete'),
    
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django_google_maps import fields as map_fields



class Amenity(models.Model):
  name = models.CharField(max_length=50)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('amenities_detail', kwargs={'pk': self.id})


class Home(models.Model):
  address = map_fields.AddressField(max_length=200)
  price = models.CharField(max_length=100)
  beds = models.IntegerField()
  baths = models.IntegerField()
  sqft = models.CharField(max_length=100)
  description = models.TextField(max_length=1000)
  amenities = models.ManyToManyField(Amenity)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.address

  def get_absolute_url(self):
    return reverse('detail', kwargs={'home_id': self.id})



class Photo(models.Model):
    url = models.CharField(max_length=200)
    home = models.ForeignKey(Home, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for home_id: {self.home_id} @{self.url}"

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Home, Amenity, Photo
import uuid
import boto3


S3_BASE_URL = 'http://s3.us-east-1.amazonaws.com/'
BUCKET = 'homebasebucket-yas'


def home(request):
  return render(request, 'home.html')


def about(request):
  return render(request, 'about.html')


@login_required
def homes_index(request):
  homes = Home.objects.filter(user=request.user)
  return render(request, 'homes/index.html', {'homes': homes})


@login_required
def homes_detail(request, home_id):
  home = Home.objects.get(id=home_id)
  # Get the amenities the home doesn't have
  amenities_home_doesnt_have = Amenity.objects.exclude(
      id__in=home.amenities.all().values_list('id'))
  return render(request, 'homes/detail.html', {
      # Add the amenities to be displayed
      'amenities': amenities_home_doesnt_have, 'home': home
  })


@login_required
def assoc_amenity(request, home_id, amenity_id):
  # Note that you can pass a amenity's id instead of the whole object
  Home.objects.get(id=home_id).amenities.add(amenity_id)
  return redirect('detail', home_id=home_id)


@login_required
def assoc_amenity_delete(request, home_id, amenity_id):
  Home.objects.get(id=home_id).amenities.remove(amenity_id)
  return redirect('detail', home_id=home_id)


@login_required
def add_photo(request, home_id):
    # attempt to collect the photo file data
    photo_file = request.FILES.get('photo-file', None)
    # use conditional logic to determine if file is present
    if photo_file:
       #if it's present, we will create a reference to the boto3 client
        s3 = boto3.client('s3')
        #create a unique id for each photo file
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # upload the photo file to aws s3
        try:
          #if successful
            s3.upload_fileobj(photo_file, BUCKET, key)
            #take the exchanged url and save it to the database
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            #1) create photo instance with photo model and provide home_id as foreign key val
            photo = Photo(url=url, home_id=home_id)
            #2) save the photo instance to the database
            photo.save()
        except Exception as error:
          # print an error message
            print('An error occurred uploading file to S3', error)
            return redirect('detail', home_id=home_id)
        return redirect('detail', home_id=home_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


class HomeCreate(LoginRequiredMixin, CreateView):
  model = Home
  fields = ['address', 'price', 'beds', 'baths', 'sqft', 'description']
  success_url = '/homes/'
  # This inherited method is called when a
  # valid home form is being submitted

  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the home
    # Let the CreateView do its job as usual
    return super().form_valid(form)


class HomeUpdate(LoginRequiredMixin, UpdateView):
  model = Home
  # Let's disallow the renaming of a home by excluding the name field!
  fields = ['address', 'price', 'beds', 'baths', 'sqft', 'description']


class HomeDelete(LoginRequiredMixin, DeleteView):
  model = Home
  success_url = '/homes/'


class AmenityList(LoginRequiredMixin, ListView):
  model = Amenity
  template_name = 'amenities/index.html'


class AmenityDetail(LoginRequiredMixin, DetailView):
  model = Amenity
  template_name = 'amenities/detail.html'


class AmenityCreate(LoginRequiredMixin, CreateView):
    model = Amenity
    fields = ['name']


class AmenityUpdate(LoginRequiredMixin, UpdateView):
    model = Amenity
    fields = ['name']


class AmenityDelete(LoginRequiredMixin, DeleteView):
    model = Amenity
    success_url = '/amenities/'

main_app/templates/amenities/detail.html
{% extends 'base.html' %} {% block content %}

<h3>Amenity Details</h3>

<div class="card">
  <a href="{% url 'amenity_detail' amenity.id %}">
    <div class="card-content">
      <span class="card-title">{{amenity.name}}</span>
    </div>
    <div class="card-action">
      <a href="{% url 'amenities_update' amenity.id %}">Edit</a>
      <a href="{% url 'amenities_delete' amenity.id %}">Delete</a>
    </div>
  </a>
</div>

{% endblock %}

main_app/templates/amenities/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Homebase</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-OISFheSMT91glMh98cDZlqoJ3PodyjQ&callback=initMap"></script>
    <script>
      $(document).ready(function(){
        // Side Menu
        $('.sidenav').sidenav({
          menuWidth: 300,
          closeOnClick: true,
          edge: 'right'
        });
        // Light box
        $('.materialboxed').materialbox();
      });
    </script>
  </head>
  <body>
      <nav class="navbar-fixed black">
        <div class="nav-wrapper">
          <ul>
            <li class="heading">
              <a href="/" class="left brand-logo">Homebase</a>
            </li>
          </ul>
          <a href="#" data-target="slide-out" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a class="waves-effect" href="{% url 'homes_create' %}">Add a Home</a></li>
            <li><a class="waves-effect" href="{% url 'index' %}">View Watchlist</a></li>
            <li><a class="waves-effect" href="{% url 'amenities_create' %}">Add an Amenity</a></li>
            <li><a class="waves-effect" href="{% url 'amenities_index' %}">View Amenities</a></li>
            <li><a class="waves-effect" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a class="waves-effect" href="{% url 'signup' %}">Sign Up</a></li>
            <li><a class="waves-effect" href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <ul id="slide-out" class="sidenav">
        {% if user.is_authenticated %}
        <li><a class="waves-effect" href="{% url 'homes_create' %}">Add a Home</a></li>
        <li><a class="waves-effect" href="{% url 'index' %}">View Watchlist</a></li>
        <li><a class="waves-effect" href="{% url 'amenities_create' %}">Add an Amenity</a></li>
        <li><a class="waves-effect" href="{% url 'amenities_index' %}">View Amenities</a></li>
        <li><a class="waves-effect" href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
        <li><a class="waves-effect" href="{% url 'signup' %}">Sign Up</a></li>
        <li><a class="waves-effect" href="{% url 'login' %}">Log In</a></li>
        {% endif %}
      </ul>
    
    <h3 class="amenities-title">Amenities</h3>

    <main class="amenities-index">
      {% for amenity in object_list %}
        <div class="card">
          <a href="{% url 'amenities_detail' amenity.id %}">
            <div class="card-content">
              <span class="card-title">{{amenity.name}}</span>
            </div>
          </a>
        </div>
      {% endfor %} 
    </main>
    <footer class="page-footer black">
      <div class="right">All Rights Reserved, © 2022 Homebase</div>
    </footer>
  </body>
</html>

<h3>Amenities</h3>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Homebase</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6n8GX8nG1FZBF87a_9-boFS2wXKX6z-o&callback=initMap"></script>
    <script>
      $(document).ready(function(){
        // Side Menu
        $('.sidenav').sidenav({
          menuWidth: 300,
          closeOnClick: true,
          edge: 'right'
        });
        // Light box
        $('.materialboxed').materialbox();
      });
    </script>
  </head>
  <body>
      <nav class="navbar-fixed black">
        <div class="nav-wrapper">
          <ul>
            <li class="heading">
              <a href="/" class="left brand-logo">Homebase</a>
            </li>
          </ul>
          <a href="#" data-target="slide-out" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a class="waves-effect" href="{% url 'homes_create' %}">Add a Home</a></li>
            <li><a class="waves-effect" href="{% url 'index' %}">View Watchlist</a></li>
            <li><a class="waves-effect" href="{% url 'amenities_create' %}">Add an Amenity</a></li>
            <li><a class="waves-effect" href="{% url 'amenities_index' %}">View Amenities</a></li>
            <li><a class="waves-effect" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a class="waves-effect" href="{% url 'signup' %}">Sign Up</a></li>
            <li><a class="waves-effect" href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <ul id="slide-out" class="sidenav">
        {% if user.is_authenticated %}
        <li><a class="waves-effect" href="{% url 'homes_create' %}">Add a Home</a></li>
        <li><a class="waves-effect" href="{% url 'index' %}">View Watchlist</a></li>
        <li><a class="waves-effect" href="{% url 'amenities_create' %}">Add an Amenity</a></li>
        <li><a class="waves-effect" href="{% url 'amenities_index' %}">View Amenities</a></li>
        <li><a class="waves-effect" href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
        <li><a class="waves-effect" href="{% url 'signup' %}">Sign Up</a></li>
        <li><a class="waves-effect" href="{% url 'login' %}">Log In</a></li>
        {% endif %}
      </ul>

    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer black">
      <div class="right">All Rights Reserved, © 2022 Homebase</div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Homebase</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
      $(document).ready(function(){
        // Side Menu
        $('.sidenav').sidenav({
          menuWidth: 300,
          closeOnClick: true,
          edge: 'right'
        });
        // Light box
        $('.materialboxed').materialbox();
      });
    </script>
  </head>
  <body>
      <nav class="navbar-fixed black">
        <div class="nav-wrapper">
          <ul>
            <li class="heading">
              <a href="/" class="left brand-logo">Homebase</a>
            </li>
          </ul>
          <a href="#" data-target="slide-out" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a class="waves-effect" href="{% url 'homes_create' %}">Add a Home</a></li>
            <li><a class="waves-effect" href="{% url 'index' %}">View Watchlist</a></li>
            <li><a class="waves-effect" href="{% url 'amenities_create' %}">Add an Amenity</a></li>
            <li><a class="waves-effect" href="{% url 'amenities_index' %}">View Amenities</a></li>
            <li><a class="waves-effect" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a class="waves-effect" href="{% url 'signup' %}">Sign Up</a></li>
            <li><a class="waves-effect" href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <ul id="slide-out" class="sidenav">
        {% if user.is_authenticated %}
        <li><a class="waves-effect" href="{% url 'homes_create' %}">Add a Home</a></li>
        <li><a class="waves-effect" href="{% url 'index' %}">View Watchlist</a></li>
        <li><a class="waves-effect" href="{% url 'amenities_create' %}">Add an Amenity</a></li>
        <li><a class="waves-effect" href="{% url 'amenities_index' %}">View Amenities</a></li>
        <li><a class="waves-effect" href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
        <li><a class="waves-effect" href="{% url 'signup' %}">Sign Up</a></li>
        <li><a class="waves-effect" href="{% url 'login' %}">Log In</a></li>
        {% endif %}
      </ul>

    <main class="home-container">
        
    </main>
    <footer class="page-footer black">
      <div class="right">All Rights Reserved, © 2022 Homebase</div>
    </footer>
  </body>
</html>

main_app/templates/homes/detail.html
{% extends 'base.html' %} {% block content %}
{% load easy_maps_tags %}
<h3>Home Details</h3>

<div>
    <div class="row card">
        {% for photo in home.photo_set.all %}
        <div class="col s12 m6 l4">
            <img class="materialboxed responsive-img card" src={{photo.url}} />
        </div>
        {% empty %}
    </div>
    
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
</div>
<form
action="{% url 'add_photo' home.id %}"
class="card-panel"
method="POST"
enctype="multipart/form-data"
>
{% csrf_token %}
<input type="file" multiple name="photo-file" />
<br />
<br />
<input type="submit" class="btn blue" value="Upload Photo" />
</form>

 {% easy_map home.address 1280 500 %}

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ home.address }}</span>
        <p>Price: {{ home.price }}</p>
        <p>Beds: {{ home.beds }}</p>
        <p>Baths: {{ home.baths }}</p>
        <p>Description: {{ home.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'homes_update' home.id %}">Edit</a>
        <a href="{% url 'homes_delete' home.id %}">Delete</a>
      </div>
    </div>
  </div>
  
   
  
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h4>Included Amenities</h4>
    {% if home.amenities.count %} {% for amenity in home.amenities.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{ amenity.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Amenities :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h4>Amenity Options</h4>
    {% if amenities.count %} {% for amenity in amenities.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{ amenity.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_amenity' home.id amenity.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn blue">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{home.address}} Has All Desired Amenities</h5>
    {% endif %}
  </div>

  {% endblock %}
</div>

main_app/templates/homes/index.html
{% extends 'base.html' %} 
{% block content %}

<h3>Watchlist</h3>


{% for home in homes %}
<div class="card home-index">
  {% comment %} <img class="activator" src="{{photo.url}}"> {% endcomment %}
  <a href="{% url 'detail' home.id %}">
    <div class="card-content">
      {% for photo in home.photo_set.all%}  
      <img src="{{ photo.url }}" class="responsive-img">
      {%empty%}
      <div class="card-panel red-text">No Photos Uploaded</div>
      {% endfor %}
      <span class="card-title">{{ home.address }}</span>
      <p>Beds: {{ home.beds }}</p>
      <p>Baths: {{ home.baths }}</p>
      <p>Sq Ft: {{ home.sqft }}</p>
      <p>Description: {{ home.description }}</p>
    </div>
  </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/amenity_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h4>
  Are you sure you want to delete
  <span class="blue-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
  {% csrf_token %}
  <input class="btn red" type="submit" value="Yes - Delete" />
  <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/amenity_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h3>Update {{ object.name }}</h3>
{% else %}
<h3>Add Amenity</h3>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input
    class="btn blue"
    type="submit"
    value="{% if object %} Update Amenity {% else %} Add Amenity {% endif %}"
  />
</form>

{% endblock %}

main_app/templates/main_app/home_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h4>
  Are you sure you want to delete
  <span class="blue-text">{{ object.address }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' home.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/home_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h3>Edit <span class="teal-text">{{object.name}}</span></h3>
{% else %}
<h3>Add Home</h3>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <br>
  <input type="submit" value="Submit" class="btn blue" />
</form>
{% endblock %}